# Generated by Django 4.0.10 on 2025-10-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zeitlabs_payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MigrationMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_table', models.CharField(max_length=100)),
                ('source_id', models.CharField(max_length=100)),
                ('target_model', models.CharField(max_length=100)),
                ('target_id', models.CharField(blank=True, max_length=100, null=True)),
                ('succeeded', models.BooleanField(default=False)),
                ('migrated_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-migrated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='migrationmap',
            index=models.Index(fields=['source_table', 'source_id', 'succeeded'], name='zeitlabs_pa_source__32ba36_idx'),
        ),
        migrations.AddIndex(
            model_name='migrationmap',
            index=models.Index(fields=['source_table', 'source_id', '-migrated_at'], name='zeitlabs_pa_source__6effb5_idx'),
        ),
    ]
