# Generated by Django 4.2.20 on 2026-03-19 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zeitlabs_payments', '0002_alter_catalogueitem_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('payment_pending', 'Payment Pending'), ('refund_requested', 'Refund Requested'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='catalogueitem',
            name='type',
            field=models.CharField(choices=[('paid_course', 'Paid Course'), ('program_bundle', 'Program Bundle')], max_length=20),
        ),
        migrations.CreateModel(
            name='BundleCourseItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bundle', models.ForeignKey(help_text='The program bundle CatalogueItem.', limit_choices_to={'type': 'program_bundle'}, on_delete=django.db.models.deletion.CASCADE, related_name='bundle_courses', to='zeitlabs_payments.catalogueitem')),
                ('course_item', models.ForeignKey(help_text='A paid_course CatalogueItem included in this bundle.', limit_choices_to={'type': 'paid_course'}, on_delete=django.db.models.deletion.CASCADE, related_name='in_bundles', to='zeitlabs_payments.catalogueitem')),
            ],
            options={
                'unique_together': {('bundle', 'course_item')},
            },
        ),
    ]
