# Generated by Django 4.2.30 on 2026-07-12 08:03

from django.db import migrations, models


def _backfill_sort_order(apps, schema_editor):  # type: ignore[no-untyped-def]
    """
    Backfill ``BundleCourseItem.sort_order`` for rows that pre-date the field.

    Existing rows used ``id`` to determine the bundle order; we mirror that
    so that reordering hasn't happened as a side-effect of this migration.
    Admins can then update ``sort_order`` on individual rows to deliberately
    change the order (e.g. to put an intro/demo course before a more
    advanced one in the post-payment "Start First Course" CTA).
    """
    BundleCourseItem = apps.get_model('zeitlabs_payments', 'BundleCourseItem')
    for bci in BundleCourseItem.objects.all():
        if bci.sort_order == 0 and bci.id > 0:
            bci.sort_order = bci.id
            bci.save(update_fields=['sort_order'])


def _noop_reverse(apps, schema_editor):  # type: ignore[no-untyped-def]
    """Reverse is a no-op: the field is kept, sort_order values stay as-is."""
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('zeitlabs_payments', '0003_add_bundlecourseitem_and_program_bundle_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bundlecourseitem',
            options={'ordering': ('sort_order', 'id')},
        ),
        migrations.AddField(
            model_name='bundlecourseitem',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Order in which this course appears inside the bundle. Lower numbers come first; ties are broken by id. Used by the post-payment "Start First Course" CTA to decide which course the learner is sent to after a successful bundle purchase.'),
        ),
        migrations.RunPython(_backfill_sort_order, _noop_reverse),
    ]
