# Generated by Django 4.2.20 on 2026-06-21 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('zeitlabs_payments', '0003_add_bundlecourseitem_and_program_bundle_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentsTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Default', help_text='Human-readable name', max_length=100)),
                ('primary', models.CharField(default='#0B7A4A', help_text='Main brand color', max_length=9)),
                ('primary_rgb', models.CharField(default='11, 122, 74', help_text='RGB values for rgba() — e.g. "27, 131, 84"', max_length=20)),
                ('secondary', models.CharField(default='#054D2E', help_text='Accent color for headers/tables', max_length=9)),
                ('success', models.CharField(default='#0B7A4A', max_length=9)),
                ('success_light', models.CharField(default='#E8F5E9', max_length=9)),
                ('error', models.CharField(default='#D32F2F', max_length=9)),
                ('error_light', models.CharField(default='#FFEBEE', max_length=9)),
                ('warning', models.CharField(default='#F57C00', max_length=9)),
                ('warning_light', models.CharField(default='#FFF3E0', max_length=9)),
                ('info', models.CharField(default='#1976D2', max_length=9)),
                ('info_light', models.CharField(default='#E3F2FD', max_length=9)),
                ('white', models.CharField(default='#FFFFFF', max_length=9)),
                ('gray_50', models.CharField(default='#FAFAFA', max_length=9)),
                ('gray_100', models.CharField(default='#F5F5F5', max_length=9)),
                ('gray_200', models.CharField(default='#EEEEEE', max_length=9)),
                ('gray_300', models.CharField(default='#E0E0E0', max_length=9)),
                ('gray_400', models.CharField(default='#BDBDBD', max_length=9)),
                ('gray_500', models.CharField(default='#9E9E9E', max_length=9)),
                ('gray_600', models.CharField(default='#757575', max_length=9)),
                ('gray_700', models.CharField(default='#616161', max_length=9)),
                ('gray_800', models.CharField(default='#424242', max_length=9)),
                ('gray_900', models.CharField(default='#212121', max_length=9)),
                ('font_family', models.CharField(default="system-ui, -apple-system, 'Segoe UI', Roboto, sans-serif", max_length=500)),
                ('site', models.OneToOneField(blank=True, help_text='Site this theme applies to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments_theme', to='sites.site')),
            ],
            options={
                'verbose_name': 'Payments Theme',
                'verbose_name_plural': 'Payments Themes',
            },
        ),
    ]
