# Generated by Django 4.0.10 on 2025-07-02 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zeitlabs_payments', '0004_auditlog_updated_at_cart_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogueitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='catalogueitem',
            name='title',
            field=models.CharField(default='seat', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='related_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zeitlabs_payments.transaction'),
        ),
    ]
