# Generated by Django 4.0.10 on 2025-07-02 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zeitlabs_payments', '0005_catalogueitem_description_catalogueitem_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
